package com.onlineBroker.InvestmentManagementService.persistence.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.LinkedList;

/*
This class represents an investment of a specific stock.
A user can have multiple investments..
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class StockInvestmentEntity {
    String investmentId;
    LinkedList<ShareEntity> sharesInPossession;
    ArrayList<ShareEntity> sharesSold;

    //break even point for investment. If market price above averagePriceOfInvestment - profit, if below - loss
    Double averagePriceOfInvestment;

    //accumulated purchase prices of all shares in possession
    Double valueOfInvestment;

    //realized profit/loss generated by selling of share(s)
    Double realizedProfitLossOfInvestment;
}
